name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  check:
    runs-on: "ubuntu-latest"
    name: "Lint & format"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Hassfest validation"
        uses: "home-assistant/actions/hassfest@master"
      - name: "HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
      - uses: "cachix/install-nix-action@v31"
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command pre-commit run --all-files
